### ISSUE TITLE
Order of couplings

### ISSUE THREAD

**Issue by VietTralala** [hsinyuan-huang/provable-ml-quantum#1]
Hi Robert! @hsinyuan-huang 
thanks for providing the code and data. However I struggle to understand the order of the provided coupling constants.

In your paper you specified the node order as follows: 

```
0 - 1 - 2 - 3
|   |   |   |
4 - 5 - 6 - 7
|   |   |   |
8 - 9 - 10 - 11
```

The couplings are provided in a simple 1d list so that I don't know what each entry in the list correspond to. For example does the first entry correspond to the edge (0,4) or (0,1) and so on? 
Could you please elaborate on that? Thanks in advance!

**Comment by hsinyuan-huang** [comment]
Hi @VietTralala !

I think the ordering is (0, 4), (0, 1), (1, 5), (1, 2), (2, 6), (2, 3), (3, 7), (4, 8), (4, 5), ....
Please let me know if you have further questions!

**Comment by VietTralala** [comment]
Thanks alot! I will try it with that ordering. I opened another issue to keep things organized
